# .github/workflows/docs.yml
name: Build & Deploy Sphinx Docs

on:
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          # path relativo alla root del repo:
          environment-file: ./anaconda/environment.yml
          activate-environment: docs-env
          clean-patched-environment-file: true

      - name: Generate API stubs
        run: |
          conda run -n docs-env --no-capture-output sphinx-apidoc \
            -f -o source/api src

      - name: Build HTML docs
        run: |
          conda run -n docs-env --no-capture-output sphinx-build \
            -b html source docs

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages
          user_name: github-actions[bot]
          user_email: github-actions[bot]@users.noreply.github.com
