# .github/workflows/docs.yml
name: Build & Deploy Sphinx Docs

on:
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          # path relativo alla root del repo:
          environment-file: ./anaconda/environment.yml
          activate-environment: docs-env
          clean-patched-environment-file: true

      - name: Generate API stubs
        shell: bash -l {0}
        run: |
          source ~/miniconda3/etc/profile.d/conda.sh   # o dove hai installato Miniconda
          conda activate docs-env
          anaconda-project run apidoc

      - name: Build HTML docs
        shell: bash -l {0}
        run: |
          source ~/miniconda3/etc/profile.d/conda.sh
          conda activate docs-env
          anaconda-project run build_docs

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages
          user_name: github-actions[bot]
          user_email: github-actions[bot]@users.noreply.github.com
